proxy:
  port: 8545
  routes:
    - id: eth
      blockchain: ethereum

cluster:
  upstreams:
    - id: proxy
      chain: ethereum
      options:
        role: primary
        validate-peers: false
        validate-syncing: false
      methods:
        enabled:
          - name: proxy_echo
      connection:
        ethereum:
          rpc:
            url: "http://localhost:9000"
